# Site Settings
baseurl: 		''
title: 			code 'n fold

name: 			code <i>'n</i> fold
description: 	Code and Origami – Software Engineering
url: 			"http://snowdj.github.io/code-n-fold"
baseurl: "/code-n-fold"

paginate: 		7
paginate_path: 	"code-n-fold/blog/page:num"

twitter: 		code_n_fold
email: 			daniel.kummer@gmail.com

disqus: 		code-n-fold
analytics: 		UA-66459836-1

copyright: 		Copyright 2015 Daniel Kummer.

# Build Settings
permalinks: 	pretty

#output settings
#permalink: '/:year/:month/:title'

gems:
  - jekyll-redirect-from

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', 'resources']
